### ISSUE TITLE
New Project wizard fails

### ISSUE THREAD

**Issue by rafaeleyng** [jknack/antlr4ide#146]
Just installed the plugin for the very first time, went to New -> Project and got this:

![image](https://cloud.githubusercontent.com/assets/4842605/19136662/c2ad4178-8b44-11e6-99e5-322acd36b3d7.png)

OS: OSX - El Capitan
Eclipse version: Mars.2 Release (4.5.2) Build id: 20160218-0600
ANTLR4 IDE version: 0.3.5

EDIT:

It might be worth to note that I installed antlr using Homebrew.

**Comment by rafaeleyng** [comment]
Just created my first .g4 file and got a similar error:

![screen shot 2016-10-05 at 10 58 45 pm](https://cloud.githubusercontent.com/assets/4842605/19138062/57e8cdc0-8b4f-11e6-87e0-f68effb9999c.png)

Full stacktrace:

```
org.eclipse.core.runtime.CoreException: Failed to create injector for com.github.jknack.antlr4ide.Antlr4 ExtensionFactory: com.github.jknack.antlr4ide.ui.Antlr4ExecutableExtensionFactory
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:59)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.WorkbenchPlugin$1.run(WorkbenchPlugin.java:294)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:289)
	at org.eclipse.ui.internal.registry.EditorDescriptor.createEditor(EditorDescriptor.java:235)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:328)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:279)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPart(CompatibilityEditor.java:63)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:99)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4781)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:572)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:536)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:396)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1166)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3252)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3167)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3149)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3144)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3108)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:541)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:500)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:360)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:167)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:268)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:233)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:275)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:251)
	at org.eclipse.jdt.internal.ui.navigator.OpenAndExpand.run(OpenAndExpand.java:50)
	at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:229)
	at org.eclipse.ui.navigator.CommonNavigatorManager$2.open(CommonNavigatorManager.java:191)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:854)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:851)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1168)
	at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:449)
	at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1275)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:278)
	at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:272)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:313)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.RuntimeException: Failed to create injector for com.github.jknack.antlr4ide.Antlr4
	at com.github.jknack.antlr4ide.ui.internal.Antlr4Activator.createInjector(Antlr4Activator.java:71)
	at com.github.jknack.antlr4ide.ui.internal.Antlr4Activator.getInjector(Antlr4Activator.java:55)
	at com.github.jknack.antlr4ide.ui.Antlr4ExecutableExtensionFactory.getInjector(Antlr4ExecutableExtensionFactory.java:26)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:51)
	... 115 more
Caused by: com.google.inject.CreationException: Guice creation errors:

1) null returned by binding at com.github.jknack.antlr4ide.ui.Antlr4UiModule.configureIStorage2UriMapperJdtExtensions(Antlr4UiModule.java:147)
 but org.eclipse.xtext.ui.containers.JavaProjectsStateHelper.uriMapperExtensions is not @Nullable
  while locating org.eclipse.xtext.ui.resource.IStorage2UriMapperJdtExtensions
    for field at org.eclipse.xtext.ui.containers.JavaProjectsStateHelper.uriMapperExtensions(Unknown Source)
  at org.eclipse.xtext.ui.containers.JavaProjectsStateHelper.class(Unknown Source)
  while locating org.eclipse.xtext.ui.containers.JavaProjectsStateHelper
    for field at org.eclipse.xtext.ui.containers.JavaProjectsState.javaProjectsHelper(Unknown Source)
  at org.eclipse.xtext.ui.containers.JavaProjectsState.class(Unknown Source)
  while locating org.eclipse.xtext.ui.containers.JavaProjectsState
    for field at org.eclipse.xtext.common.types.xtext.ui.JdtIndexedJvmTypeAccess.javaProjectsState(Unknown Source)
  while locating org.eclipse.xtext.common.types.xtext.ui.JdtIndexedJvmTypeAccess
  while locating org.eclipse.xtext.common.types.access.impl.IndexedJvmTypeAccess
    for field at org.eclipse.xtext.common.types.access.AbstractTypeProviderFactory.indexedJvmTypeAccess(Unknown Source)
  while locating org.eclipse.xtext.common.types.access.ClasspathTypeProviderFactory
    for field at org.eclipse.xtext.common.types.xtext.ClasspathBasedTypeScopeProvider.typeProviderFactory(Unknown Source)
  while locating org.eclipse.xtext.common.types.xtext.ClasspathBasedTypeScopeProvider
  while locating org.eclipse.xtext.common.types.xtext.AbstractTypeScopeProvider
    for field at org.eclipse.xtext.common.types.xtext.TypesAwareDefaultGlobalScopeProvider.typeScopeProvider(Unknown Source)
  at org.eclipse.xtext.common.types.xtext.TypesAwareDefaultGlobalScopeProvider.class(Unknown Source)
  while locating org.eclipse.xtext.common.types.xtext.TypesAwareDefaultGlobalScopeProvider
  while locating org.eclipse.xtext.scoping.IGlobalScopeProvider
    for field at org.eclipse.xtext.ui.editor.templates.CrossReferenceTemplateVariableResolver.globalScopeProvider(Unknown Source)
  at org.eclipse.xtext.ui.editor.templates.CrossReferenceTemplateVariableResolver.class(Unknown Source)
  while locating org.eclipse.xtext.ui.editor.templates.CrossReferenceTemplateVariableResolver
    for parameter 0 at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextType.setCrossReferenceResolver(Unknown Source)
  while locating org.eclipse.xtext.ui.editor.templates.XtextTemplateContextType
  at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry.<init>(Unknown Source)
  at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry.class(Unknown Source)
  while locating org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry
  while locating org.eclipse.jface.text.templates.ContextTypeRegistry
    for field at org.eclipse.xtext.ui.codetemplates.ui.registry.LanguageRegistrar.contextTypeRegistry(Unknown Source)
  at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
  while locating org.eclipse.xtext.ui.codetemplates.ui.registry.LanguageRegistrar

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:183)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.github.jknack.antlr4ide.ui.internal.Antlr4Activator.createInjector(Antlr4Activator.java:67)
	... 118 more
```

**Comment by HSorensen** [comment]
Did you resolve this?
Which version of xtend are you using?

Henrik

**Comment by rafaeleyng** [comment]
No, I just gave up.

I don't know what is xtend.

**Comment by arifogel** [comment]
Should be fixed now. Please update to 0.3.6 from the Marketplace and try again. If you do not respond within two weeks, I will close as resolved.

**Comment by rafaeleyng** [comment]
@arifogel 

Updated to 0.3.6, and both errors I reported above seems to be solved.
I didn't test anything besides that.
